# generated by datamodel-codegen:
#   filename:  organization_fr-schema.json
#   timestamp: 2022-01-28T15:14:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class OrganizationFr(BaseModel):
    __root__: Any = Field(
        ...,
        description='Spécification du modèle de données organization relatif au catalogue des jeux de données Santé Environnement du GD4H',
        title='Organization - fr',
    )
